# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Genex
version:      0.07
version_from: lib/Regexp/Genex.pm
installdirs:  site
requires:
    String::Escape:                2002.001
    YAPE::Regex:                   3.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
